### ISSUE TITLE
Feature: Allow inclusion of JQuery from Google's servers (and/or others)

### ISSUE THREAD

**Issue by DOCaCola** [gobezu/jbetolo#14]
This might be also a good idea for other libraries.

Interesting read:
http://encosia.com/3-reasons-why-you-should-let-google-host-jquery-for-you/

Especially caching might be a good reason, since the JQuery library then might have already been loaded from a visit to another website that uses the same approach anyway.

Another quite useful javascript plugin for joomla offers this: InterExt - http://extensions.joomla.org/extensions/core-enhancements/performance/scripts-optimization/18499 . But jbetolo and InterExt combined don't always work fine.

**Comment by gobezu** [comment]
Jbetolo now supports loading from cdnjs.com which supports far more libraries to offer
