### ISSUE TITLE
Problems with mediaqueries

### ISSUE THREAD

**Issue by mackelito** [gobezu/jbetolo#35]
When enabling the plugin all works as it should... but after some time (like after x hours) the responsive behavior changes??

The first image shows the same site refreshed after 2h... works if I clear the joomla cache (second image)..

I use it on www.homeofsweden.se if you want to check it out.
(using the template "afterburner" from rockettheme)

![befor cache cleared](https://f.cloud.github.com/assets/598463/1459976/4363b610-4405-11e3-9d8e-4158304b2fe4.png)
![cache cleared](https://f.cloud.github.com/assets/598463/1459977/437ddbc6-4405-11e3-8a3e-489678b2b061.png)

**Comment by mackelito** [comment]
Hmmm.. I just noticed that also some of the JS features stopped working :/

**Comment by gobezu** [comment]
Please contact me over at jproven.com and we will try to deal with it.
Thank you!
